sudo: required
language: node_js
node_js:
- '7'
services:
  - docker
env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - PATH="${HOME}/google-cloud-sdk/bin:${PATH}"
  - GCLOUD_PROJECT='icanhelpyouwiththat-149304'
  - PROJECT_ID="${GCLOUD_PROJECT}"
  - ZONE='us-central1-c'
  - CLUSTER_ID='stage'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - if [ ! -d "${HOME}/google-cloud-sdk" ]; then curl https://sdk.cloud.google.com | bash; fi
  - gcloud --quiet version
  - gcloud --quiet components install kubectl
  - kubectl version --client=true
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
script: "./node_modules/.bin/mocha"
before_deploy:
  - echo $GCLOUD_KEY | base64 --decode > ${PWD}/gcloud.json
  - export GOOGLE_APPLICATION_CREDENTIALS="${PWD}/gcloud.json"
  - export KUBECONFIG="${PWD}/.kube/config"
  - gcloud --quiet auth activate-service-account --key-file "${GOOGLE_APPLICATION_CREDENTIALS}"
  - gcloud --quiet config set project "${PROJECT_ID}"
  - gcloud --quiet config set compute/zone "${ZONE}"
  - kubectl config use-context "${CLUSTER_ID}"
  - ssh-keygen -f ~/.ssh/google_compute_engine -N ""
  - bash -l ./gcloud.sh docker -a
  - docker build -t us.gcr.io/icanhelpyouwiththat-149304/backend:latest .
  - docker push us.gcr.io/icanhelpyouwiththat-149304/backend:latest > /dev/null
  - gcloud container clusters get-credentials stage --zone us-central1-c
  - export KUBECONFIG="${PWD}/.kube/config"
  - kubectl delete pods -l name=backend
notifications:
  slack:
    secure: YTBdjS53PzDiza/8HjMmOit+Wfs61T9hgpetg6SkiP9/sgizyfXFl6Bp/J7f8pxgo5oZwTyXXbtv8+Itb1puzsnbM4bJZX/M6uCxy23d7Mjpiwowxy6frC4S6hs8EhDgm+TbWQx/RoHYriOLLV4GbfYWlL6CxPqB7wFdXVEH8HBLLWfUCzKKHq20gnYhT4KJX05xgtaH48qkz0O3uBXEeJX8AZe/c/Lb5pZRzXgGmn+VqjuwAe1cD8su9LLBOP1wdq5xvNcsXZ9PoEARTi6iZINQctAvYz9lfdymZAJ9NpZ3iopBHFP6GYPLHPvYTVQCLNpLaZAgEGBBnH9+8jway+tfZ2dViLNmAadiDMjtley6JbY/aJrNqhmfpDp9sx6BzaAtnC8GugSnOTJ99FHAx/0W8Ylj1Z80rZDrBRCA9apbqdQUec3FdU6IsptKsT1/8F0uedirwqvV87jQ63TXskbl2zLxKOoewB7jYbnJA0VH/oeu5DTbm+tmRzwLPgds0vMh32zox9OTCgGqR2C5h7OVqGUIUAmdz0tq+FhQ52EcQrPJ/DT2U/FgACKPP4z+jjvKNtCPxPYjjOf7EkQB3ZsAxDq7bY9UzfT+J2dEa91oRzXIOpIqsBZvJ9RGPbJxMKFHQcmo1kU/nolhTvhiOdsubxL3lbnHn0bo9E7QHXw=
