apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    name: backend
    env: production
    role: proxy
spec:
  type: NodePort
  ports:
      - port: 80
        name: http
        targetPort: 3000
        protocol: TCP
  selector:
    name: backend
