apiVersion: v1
kind: ReplicationController
metadata:
  generateName: backend-master-
  labels:
    name: backend
    version: v0.0.0
spec:
  replicas: 1
  selector:
    name: backend
    version: v0.0.0
  template:
    metadata:
      labels:
        name: backend
        version: v0.0.0
    spec:
      volumes:
        - name: "pp"
          secret:
            secretName: pp
      containers:
        - name: backend
          image: us.gcr.io/icanhelpyouwiththat-149304/backend:latest
          command: ["/bin/bash","-c"]
          args: ["./node_modules/.bin/cross-env NODE_ENV=production node ./build/backend.js"]
          env:
          - name: NODE_ENV
            value: production
          ports:
            - containerPort: 3000
              name: http
          volumeMounts:
            - mountPath: "/tmp/pp"
              name: "pp"
