CREATE DATABASE ichuwt;
USE ichuwt;

CREATE TABLE PROFILE (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(150),
    karma_points INT,
    email VARCHAR(150),
    mobile_phone VARCHAR(150),
    geo_location VARCHAR(25),
    zip_code VARCHAR(15),
    profile_type TINYINT,
    mission VARCHAR(500),
    admin TINYINT,
    likes INT,
    invites INT,
    password VARCHAR(60),
    linked_acct VARCHAR(500),
    status TINYINT,
    PRIMARY KEY(ID)
);

CREATE TABLE ACTIVITY (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    date_time DATETIME,
    geo_location VARCHAR(25),
    goal VARCHAR(5000),
    status TINYINT,
    PRIMARY KEY(ID), name VARCHAR(50)
);

CREATE TABLE ORGPROFILE_ACTIVITY (
    PROFILE_ID BIGINT NOT NULL,
    ACTIVITY_ID BIGINT NOT NULL,
    FOREIGN KEY (`PROFILE_ID`) REFERENCES `PROFILE` (`ID`) ON DELETE CASCADE,
    FOREIGN KEY (`ACTIVITY_ID`) REFERENCES `ACTIVITY` (`ID`) ON DELETE CASCADE
);

CREATE TABLE SKILL (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(75),
    description VARCHAR(5000),
    PRIMARY KEY(ID)
);

CREATE TABLE INVITE (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    status TINYINT,
    unique_code BIGINT,
    PROFILE_ID BIGINT NOT NULL,
    INV_PROFILE_ID BIGINT NOT NULL,
    email VARCHAR(150),
    PRIMARY KEY(ID),
    FOREIGN KEY (`PROFILE_ID`) REFERENCES `PROFILE` (`ID`) ON DELETE CASCADE,
    FOREIGN KEY (`INV_PROFILE_ID`) REFERENCES `PROFILE` (`ID`) ON DELETE CASCADE
);

CREATE TABLE ACTIVITY_SKILL (
    SKILL_ID BIGINT NOT NULL,
    ACTIVITY_ID BIGINT NOT NULL,
    FOREIGN KEY (`SKILL_ID`) REFERENCES `SKILL` (`ID`) ON DELETE CASCADE,
    FOREIGN KEY (`ACTIVITY_ID`) REFERENCES `ACTIVITY` (`ID`) ON DELETE CASCADE
);

CREATE TABLE SKILL_PROFILE (
    PROFILE_ID BIGINT NOT NULL,
    SKILL_ID BIGINT NOT NULL,
    FOREIGN KEY (`PROFILE_ID`) REFERENCES `PROFILE` (`ID`) ON DELETE CASCADE,
    FOREIGN KEY (`SKILL_ID`) REFERENCES `SKILL` (`ID`) ON DELETE CASCADE
);

CREATE TABLE INDPROFILE_ACTIVITY (
    PROFILE_ID BIGINT NOT NULL,
    ACTIVITY_ID BIGINT NOT NULL,
    STATUS BIGINT,
    FOREIGN KEY (`PROFILE_ID`) REFERENCES `PROFILE` (`ID`) ON DELETE CASCADE,
    FOREIGN KEY (`ACTIVITY_ID`) REFERENCES `ACTIVITY` (`ID`) ON DELETE CASCADE
);